package com.github.dateapp.gui;

import com.github.dateapp.User;
import com.github.dateapp.gui.pnl.PnlViewUser;
import java.awt.Frame;
import javax.swing.JPanel;

/**
 * View User Dialog. (05 May 2018 8:54:39 PM).
 *
 * @author Matthew Van der Bijl (xq9x3v31)
 */
public class DialogViewUser extends javax.swing.JDialog {

    /**
     * Creates new form Dialog View User.
     *
     * @param parent
     * @param user The user to be shown
     */
    public DialogViewUser(Frame parent, User user) {
        super(parent, true);
        this.initComponents();
        super.setTitle(user.getName());
        super.setLocationRelativeTo(null);
        addDetails(new PnlViewUser(parent, user));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.<strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetails = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDetails.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDetails(JPanel pnl) {
        System.out.println(pnl.getClass().getSimpleName());

        this.pnlDetails.removeAll();
        this.pnlDetails.add(pnl);
        this.pnlDetails.revalidate();
        this.pnlDetails.repaint();
    }

    //<editor-fold defaultstate="collapsed" desc="Generated varibles">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDetails;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
