package com.github.dateapp.gui;

import com.github.dateapp.User;
import com.github.dateapp.Util;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 * View Image Dialog. (05 May 2018 12:02:25 PM).
 *
 * @author Matthew Van der Bijl (xq9x3wv31)
 */
public class DialogViewImage extends JDialog {

    /**
     * Creates new form Dialog View Image.
     *
     * @param user
     * @param parent
     */
    // Needs to br Frame, not JFrame
    public DialogViewImage(User user, Frame parent) {
        super(parent, false);
        this.initComponents();
        this.lblIcon.setText("");
        this.lblIcon.setIcon(new ImageIcon(Util.resize(user.getProfilePic(), 400, 300)));
        super.setTitle(user.getName());
        super.setLocationRelativeTo(parent);
//        super.pack();
    }

    public DialogViewImage(FrameMain parent) {
        this(parent.getUser(), parent);
        super.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.</strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        lblIcon.setText("IMG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIcon)
                .addGap(0, 381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIcon)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="generated varibles">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
