package com.github.dateapp.gui;

import com.github.dateapp.User;
import com.github.dateapp.ViewPanel;
import com.github.dateapp.gui.pnl.PnlEditInformation;
import com.github.dateapp.gui.pnl.PnlHelp;
import com.github.dateapp.gui.pnl.PnlMatchFinder;
import com.github.dateapp.gui.pnl.PnlMatches;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Match Finder Frame. Created by Matthew at 26 Apr 2018 1:59:52 PM.
 *
 * @author Matthew Van der Bijl (xq9x3wv31)
 */
public final class FrameMain extends javax.swing.JFrame {

    /**
     * The active user.
     */
    private final User user;

    /**
     * Creates new form Match Finder Match.
     *
     * @param user
     * @param parent
     */
    public FrameMain(User user, Component parent) {
        this.initComponents();

        this.user = user;
        this.pnlButtons.setLayout(new GridLayout(0, 1));
        this.pnlData.setLayout(new GridLayout(0, 1));

        // --
        super.setTitle("~ DateApp ~");
        super.setResizable(false);
        super.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.</strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        pnlButtons = new javax.swing.JPanel();
        btnFindMatch = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnEditInfo = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogut = new javax.swing.JButton();
        pnlData = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        pnlButtons.setBackground(new java.awt.Color(250, 250, 250));
        pnlButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFindMatch.setBackground(new java.awt.Color(102, 102, 255));
        btnFindMatch.setText("Find a match");
        btnFindMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMatchActionPerformed(evt);
            }
        });

        btnMatches.setBackground(new java.awt.Color(102, 102, 255));
        btnMatches.setText("Matches");
        btnMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchesActionPerformed(evt);
            }
        });

        btnEditInfo.setBackground(new java.awt.Color(102, 102, 255));
        btnEditInfo.setText("Edit Information");
        btnEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(102, 102, 255));
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(102, 102, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogut.setBackground(new java.awt.Color(102, 102, 255));
        btnLogut.setText("Logoff");
        btnLogut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFindMatch)
                    .addComponent(btnMatches)
                    .addComponent(btnHelp)
                    .addComponent(btnExit)
                    .addComponent(btnEditInfo)
                    .addComponent(btnLogut))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFindMatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pnlData.setBackground(new java.awt.Color(250, 250, 250));
        pnlData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblWelcome.setText("Welcome!");
        lblWelcome.setToolTipText("Welcome!");

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataLayout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(251, 251, 251))
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblWelcome)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Toolkit.getDefaultToolkit().beep();
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to close "
                + "DataApp?", "Are you sure?", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.out.println("Goodbye(:");
            super.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        changePannel(new PnlHelp(this));
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoActionPerformed
        changePannel(new PnlEditInformation(this));
    }//GEN-LAST:event_btnEditInfoActionPerformed

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        changePannel(new PnlMatches(this));
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnFindMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMatchActionPerformed
        changePannel(new PnlMatchFinder(this));
    }//GEN-LAST:event_btnFindMatchActionPerformed

    private void btnLogutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogutActionPerformed
        System.out.println("logoff");
        Toolkit.getDefaultToolkit().beep();
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to logoff?",
                "Are you sure?", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            new FrameLogin(this).setVisible(true);
            super.dispose();
        }
    }//GEN-LAST:event_btnLogutActionPerformed

    public void changePannel(JPanel pnl) {
        System.out.println(pnl.getClass().getSimpleName());

        for (Component cmp : pnlData.getComponents()) {
            if (cmp instanceof ViewPanel) {
                ((ViewPanel) cmp).dispose();
            }
        }

        this.pnlData.removeAll();
        this.pnlData.add(pnl);
        this.pnlData.revalidate();
        this.pnlData.repaint();
    }

    @Override
    public void dispose() {
        for (Component cmp : pnlData.getComponents()) {
            if (cmp instanceof ViewPanel) {
                ((ViewPanel) cmp).dispose();
            }
        }
        super.dispose();
    }

    /**
     * @return The active user
     */
    public User getUser() {
        return this.user;
    }

    //<editor-fold defaultstate="collapsed" desc="Generated Varibles">  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditInfo;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindMatch;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogut;
    private javax.swing.JButton btnMatches;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlData;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
