package com.github.dateapp.gui.pnl;

import com.github.dateapp.Database;
import com.github.dateapp.User;
import com.github.dateapp.Util;
import com.github.dateapp.ViewPanel;
import com.github.dateapp.gui.DialogViewImage;
import com.github.dateapp.gui.FrameMain;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 * Information editor panel.
 *
 * @author Matthew Van der Bijl (xq9xwv31)
 */
public final class PnlEditInformation extends ViewPanel {

    private FrameMain parent;

    /**
     * Creates new form PnlEditInformation.
     *
     * @param parent parent main frames
     */
    public PnlEditInformation(FrameMain parent) {
        super(new GridLayout(0, 1));
        this.initComponents();

        this.parent = parent;
        this.lblPicture.setLayout(new GridLayout(0, 1));
        this.lblPicture.setText("");
        setImage();

        try {
            Statement stmt = Database.getStatement();
            ResultSet rs = stmt.executeQuery("SELECT genderName FROM Gender");
            while (rs.next()) {
                this.cmbGender.addItem(rs.getString(1));
            }
            rs.close();
            stmt.close();
        } catch (SQLException sqle) {
            Util.err(sqle, parent);
        }

        try {
            Statement stmt = Database.getStatement();
            ResultSet rs = stmt.executeQuery("SELECT DISTINCT hobbyName FROM Hobby");
            while (rs.next()) {
                this.cmbHobbies.addItem(rs.getString(1));
            }
            rs.close();
            stmt.close();
        } catch (SQLException sqle) {
            Util.err(sqle, parent);
        }

        User user = parent.getUser();
        this.txtFirstName.setText(user.getFirstName());
        this.txtLastName.setText(user.getLastName());
        this.txtPhoneNumber.setText(user.getPhoneNumber());
        this.txtUsername.setText(user.getUserName());
        this.txtPasswdA.setText(user.getPasswsd());
        this.txtPasswdB.setText(user.getPasswsd());
        this.cmbGender.setSelectedItem(user.getGender());

        if (cmbHobbies.getSelectedObjects() == null) {
            this.cmbHobbies.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.</strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdateProfilePic = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPasswdA = new javax.swing.JPasswordField();
        txtPasswdB = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cmbHobbies = new javax.swing.JComboBox<>();
        lblHobbies = new javax.swing.JLabel();
        btnAddHoby = new javax.swing.JButton();
        btnRemoveHobby = new javax.swing.JButton();
        pnlProfilePictue = new javax.swing.JPanel();
        lblPicture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Gender");

        btnSave.setBackground(new java.awt.Color(102, 102, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdateProfilePic.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdateProfilePic.setText("Udate Profile Picture");
        btnUpdateProfilePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfilePicActionPerformed(evt);
            }
        });

        txtPasswdA.setToolTipText("Password");

        txtPasswdB.setToolTipText("Confirm Password");

        jLabel5.setText("Username");

        lblHobbies.setText("Hobbies");

        btnAddHoby.setBackground(new java.awt.Color(102, 102, 255));
        btnAddHoby.setText("Add");
        btnAddHoby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHobyActionPerformed(evt);
            }
        });

        btnRemoveHobby.setBackground(new java.awt.Color(102, 102, 255));
        btnRemoveHobby.setText("Remove");
        btnRemoveHobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveHobbyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHobbies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLastName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFirstName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumber)))
                            .addComponent(btnUpdateProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPasswdA)
                            .addComponent(txtPasswdB)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbHobbies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddHoby, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveHobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswdB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHobbies)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(cmbHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHoby)
                    .addComponent(btnRemoveHobby))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateProfilePic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap())
        );

        pnlProfilePictue.setBackground(new java.awt.Color(250, 250, 250));
        pnlProfilePictue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPicture.setText("jLabel5");
        lblPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPictureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlProfilePictueLayout = new javax.swing.GroupLayout(pnlProfilePictue);
        pnlProfilePictue.setLayout(pnlProfilePictueLayout);
        pnlProfilePictueLayout.setHorizontalGroup(
            pnlProfilePictueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilePictueLayout.createSequentialGroup()
                .addComponent(lblPicture)
                .addGap(0, 254, Short.MAX_VALUE))
        );
        pnlProfilePictueLayout.setVerticalGroup(
            pnlProfilePictueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfilePictueLayout.createSequentialGroup()
                .addComponent(lblPicture)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfilePictue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProfilePictue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            User user = this.parent.getUser();

            if (!txtPasswdA.getText().equals(txtPasswdB.getText())) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(parent, "Password do not match.", "Failed",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            user.setFirstName(Util.str(txtFirstName.getText()));
            user.setLastName(Util.str(txtLastName.getText()));
            user.setPasswsd(Util.str(txtPasswdA.getText()));
            user.setPhoneNumber(Util.phoneNumber(Util.str(txtPhoneNumber.getText())));
            user.setUserName(Util.str(txtUsername.getText()));
            user.setGender(Util.str(cmbGender.getSelectedItem().toString()));

            user.update(parent);
        } catch (Exception ex) {
            Util.err(ex, parent);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateProfilePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfilePicActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(parent);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                this.parent.getUser().setProfilePic(ImageIO.read(jfc.getSelectedFile()));
                this.setImage();
            } catch (IOException ioe) {
                Util.err(ioe, parent);
            }
        }
    }//GEN-LAST:event_btnUpdateProfilePicActionPerformed

    private void btnAddHobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHobyActionPerformed
        try {
            String name = JOptionPane.showInputDialog(parent, "What is the name of "
                    + "your hobby?", "What is the name?", JOptionPane.QUESTION_MESSAGE);
            Util.str(name);
            String description = JOptionPane.showInputDialog(parent, "What is the description of "
                    + "your hobby?", "What is the description?", JOptionPane.QUESTION_MESSAGE);
            Util.str(description);

            String q = String.format("call add_hobby('%s', '%s')", name, description);

            System.out.println(q);

            Statement stmt = Database.getStatement();

            if (!stmt.execute(q)) {
//                JOptionPane.showMessageDialog(parent, "Insert Sucessul", "Added",
//                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(parent, "Failed to add Sucessully", "Failed",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            q = String.format("INSERT INTO person_hobby (userID, hobbyID) VALUES (%d,%d)", parent.getUser().getID(), h(name));
            System.out.println(q);

            if (!stmt.execute(q)) {
                JOptionPane.showMessageDialog(parent, "Removed Sucessul", "Removed",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(parent, "Failed to remove Sucessully", "Failed",
                        JOptionPane.ERROR_MESSAGE);
            }

            stmt.close();
            this.cmbHobbies.addItem(name);
        } catch (Exception ex) {
            Util.err(ex, parent);
        }

    }//GEN-LAST:event_btnAddHobyActionPerformed

    private void btnRemoveHobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveHobbyActionPerformed
        // validation:
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "
                + "this hobby?", "Are you sure?", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) != JOptionPane.YES_OPTION) {
            return;
        }
        // --

        try {
            String q = String.format("DELETE FROM `dateing_database`.`hobby`\n"
                    + "WHERE hobbyName = '%s'", cmbHobbies.getSelectedItem().toString());

            System.out.println(q);

            try {
                Statement stmt = Database.getStatement();

                if (!stmt.execute(q)) {
                    JOptionPane.showMessageDialog(parent, "Removed Sucessul", "Removed",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(parent, "Failed to remove Sucessully", "Failed",
                            JOptionPane.ERROR_MESSAGE);
                }

                stmt.close();
            } catch (SQLException sqle) {
                sqle.printStackTrace(System.err);
            }

            this.parent.dispose();
            FrameMain main = new FrameMain(parent.getUser(), parent);
            main.changePannel(new PnlEditInformation(main));
            main.setVisible(true);
        } catch (NullPointerException npe) {
            Util.err(npe, parent);
        }
    }//GEN-LAST:event_btnRemoveHobbyActionPerformed

    private int h(String name) throws SQLException {
        int rtn = 1;
        Statement stmt = Database.getStatement();
        String q = String.format("SELECT hobbyID FROM hobby WHERE hobbyName = '%s'", name);
        System.out.println(q);
        ResultSet rs = stmt.executeQuery(q);
        while (rs.next()) {
            rtn = rs.getInt(1);
        }
        rs.close();
        stmt.close();
        return rtn;
    }

    private void lblPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPictureMouseClicked
        new DialogViewImage(parent).setVisible(true);
    }//GEN-LAST:event_lblPictureMouseClicked

    private void setImage() {
        try {
            this.lblPicture.setIcon(new ImageIcon(Util.resize(parent.getUser().getProfilePic(),
                    380,
                    410
            )));
            this.lblPicture.setText("");
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    //<editor-fold defaultstate="collapsed" desc="Generated Varibles">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHoby;
    private javax.swing.JButton btnRemoveHobby;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateProfilePic;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbHobbies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblHobbies;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JPanel pnlProfilePictue;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPasswdA;
    private javax.swing.JPasswordField txtPasswdB;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
