package com.github.dateapp.gui.pnl;

import com.github.dateapp.ViewPanel;
import com.github.dateapp.gui.FrameMain;

/**
 * Help panel.
 *
 * @author Matthew Van der Bijl (xq9xwv31)
 */
public class PnlHelp extends ViewPanel {

    /**
     * Creates new form PnlHelp.
     *
     * @param parent parent main frame
     */
    public PnlHelp(FrameMain parent) {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.</strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(250, 250, 250));

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setLineWrap(true);
        txtOutput.setRows(5);
        txtOutput.setText("There is need a need for the creation of a new online dating application (app). This app needs to be integrated with a fully functional MySQL database and can be created with any programming language in any system. The system will make use of a MySQL database to store data and will be interacted with using Structured Query Language (SQL). This new online dating app with be developed by following design methodologies presented by Connolly and Begg (2015). The system will need to ensure entity integrity.\n\nAn adaptation of Connolly and Begg (2015) suggested methodology has been used in the development of the online dating system. All user interfaces (UI) and other interactive systems have been designed following design principles and heuristic considerations suggested by Rogers, et al. (2011).\n\nThe final system will make use moderns design principles as suggested by Nielsen (1994), Valacich, et al. (2015), Bennet, et al. (2010) and Preece, et al. (2015). Modern best practices and modern object orientated programming concepts will be employed as suggested by Gaddis (2016), Deitel and Deitel (2012), Weisfeld (2013), Pretorius and Erasmus (2012) and Drake (2014).\nAll Graphical User Interfaces (GUI) have been made using the NetBeans Integrated Development Environment (IDE). The SQL statements below were used to create the database.\n");
        txtOutput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Generated Varibles">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
